### ISSUE TITLE
V2.1 get_transaction_data() not isolating a single account when passing an id

### ISSUE THREAD

**Issue by dsteiner10** [mintapi/mintapi#485] opened 2022-06-12 15:53 UTC
Version 1.x allowed for getting transactions from a single account.  It appears that get_transaction_data() accepts an id field, but regardless of which id I pass, it seems to return all transactions for all accounts (up to the limit).

**Comment by burkematthew** [comment] 2022-06-16 12:12
@dsteiner10 can you provide a snippet of the code you are using to show the behavior?

It does look like we are passing the `id` to the endpoint if supplied, so I'll be curious to know if that's simply not what Mint wants.

**Comment by chdavis8** [comment] 2022-06-22 23:03
I'm having the same issue.  I have verified that you are passing the id to mint using print to show the url you are using:
#### account id is: 11277025_11182526
**** url before id appended: https://mint.intuit.com/pfm/v1/transactions?limit=5000&
**** url after id appended: https://mint.intuit.com/pfm/v1/transactions?limit=5000&id=11277025_11182526&

I think the issue is that mint doesn't recognize it as a valid filter.  What I get back is data for all my accounts.  This is the first part of what is returned to me.  The first transaction (for example) is from another account and you can see the id does not match:
[{'type': 'CashAndCreditTransaction', 'id': '11277025_2497679463_0', 'accountId': '11277025_12036151', 'accountRef': {...}, 'date': '2022-06-21', 'description': 'TARGET DEBIT CRD : ACH TRAN', 'category': {...}, 'amount': -17.77, 'status': 'POSTED', ...}, {'type': 'CashAndCreditTransaction', 'id': '11277025_2497679462_0', 'accountId': '11277025_12036151', 'accountRef': {...}, 'date': '2022-06-21', 'description': 'TARGET DEBIT CRD : ACH TRAN', 'category': {...}, 'amount': -6.44, 'status': 'POSTED', ...}, {'type': 'CashAndCreditTransaction', 'id': '11277025_2497303724_0', 'accountId': '11277025_10967816', 'accountRef': {...}, 'date': '2022-06-21', 'description': 'WITHDRAWAL Debit Car... 30 #5421 ', 'category': {...}, 'amount': -8.53, 'status': 'POSTED', ...}, {'type':

**Comment by dsteiner10** [comment] 2022-06-24 16:14
Here is the code that I was previously running on 1.x:

I found the same thing that chdavis8 found.  mintapi is passing the id in the url, but it doesn't seem like mint does anything with the id.

`# Get basic account information
trans_dict=[]
roi_accts = ['CK','SV','NT','CC','RE','RL','RT','SL','IV','VE','VL','ED']
account_info = mint.get_account_data()

for num,account in enumerate(account_info[:5]):
    if account["name"].startswith(tuple(roi_accts)):
        print(num,"-",account["name"], account['id'])
        trans_dict.append(mint.get_transaction_data(limit=10000, start_date=start_date, include_investment=False,id=account["id"]))
        #print(trans_dict[-1])
    else:
        print("###################ACCOUNT NOT TRACKED:",account["name"],"###########################")`

**Comment by burkematthew** [comment] 2022-06-25 00:23
Yes I found the same thing. I may just throw in a filter to the data returned from the API for the time being.

**Comment by burkematthew** [comment] 2022-07-05 11:42
Actually, I'm going to hold off on the idea mentioned as #509 will most definitely address this need.

**Comment by burkematthew** [comment] 2022-07-14 02:33
I'm going to close this one out in favor of the linked issue.

**Closed by burkematthew** 2022-07-14 02:33 UTC
