### ISSUE TITLE
mint.get_accounts() does not work after successful login

### ISSUE THREAD

**Issue by smnlng** [mintapi/mintapi#147] opened 2018-07-08 03:23 UTC
Running python 3.6 with selenium installed. After the initial code 

`import mintapi
mint = mintapi.Mint("email", "password")`

There is a successful login to Mint using a new instance of Chrome. However, attempting to use 
`mint.get_accounts()` or `mint.get_transactions_csv(include_investment=False)`

Creates a new window to http://127.0.0.1:51907/ and nothing happens. Chromedriver reports the following:

` [3020:6080:0707/232340.899:ERROR:install_util.cc(589)] Unable to create registry key HKLM\SOFTWARE\Policies\Google\Chrome for reading result=2`

`DevTools listening on ws://127.0.0.1:52065/devtools/browser/<snip>
[3020:6080:0707/232342.468:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context. `

Any suggestions?

**Comment by jaron-l** [comment] 2021-09-21 18:11
This is a duplicate of #245, which has a fix that has been merged. Let us know if you continue to have issues.

**Closed by jaron-l** 2021-09-21 18:11 UTC
