### ISSUE TITLE
(selenium.common.exceptions.WebDriverException: Message: disconnected: received Inspector.detached event) when calling get_transaction_data()

### ISSUE THREAD

**Issue by carlosverastegui** [mintapi/mintapi#579] opened 2022-12-06 08:09 UTC
### Describe the bug
When I attempt to use mintapi from Python and call get_transaction_data(), mintapi opens up Chrome, logs in, and gets to the homepage just fine. However, while at the homepage a few seconds later the program crashes with the error shown in the title. This wasn't occurring until Chrome needed to be updated to 108 and MintAPI to 2.11.

### What version of MintAPI are you using?
MintAPI is on 2.11 and Selenium is on 4.7.2.

### What command[s] did you run / steps to reproduce?
I ran a python script that contains the following credentials:

credentials = keyring.get_credential("...", None)

 mint = mintapi.Mint(
        credentials.username, 
        credentials.password,
        mfa_method = 'soft-token',
        mfa_token="...",
        wait_for_sync=False,
    )

### Stacktrace/error received:
selenium.common.exceptions.WebDriverException: Message: disconnected: received Inspector.detached event
  (Session info: chrome=108.0.5359.95)
Stacktrace:
Backtrace:
        (No symbol) [0x0063F243]
        (No symbol) [0x005C7FD1]
        (No symbol) [0x004BD04D]
        (No symbol) [0x004B0A79]
        (No symbol) [0x004B06F1]
        (No symbol) [0x004AFB0B]
        (No symbol) [0x004AFA5C]
        (No symbol) [0x004AE7E8]
        (No symbol) [0x004AEDC2]
        (No symbol) [0x004ADC55]
        (No symbol) [0x004B419D]
        (No symbol) [0x004AF703]
        (No symbol) [0x004AE7E8]
        (No symbol) [0x004AEDC2]
        (No symbol) [0x004ADC55]
        (No symbol) [0x004A7E66]
        (No symbol) [0x004AD735]
        (No symbol) [0x004ACEE0]
        (No symbol) [0x004ACB37]
        (No symbol) [0x004BE5F3]
        (No symbol) [0x004A20A7]
        (No symbol) [0x004A238C]
        (No symbol) [0x00512869]
        (No symbol) [0x00508553]
        (No symbol) [0x004E163C]
        (No symbol) [0x004E269D]
        GetHandleVerifier [0x008D9A22+2655074]
        GetHandleVerifier [0x008CCA24+2601828]
        GetHandleVerifier [0x006E8C0A+619850]
        GetHandleVerifier [0x006E7830+614768]
        (No symbol) [0x005D05FC]
        (No symbol) [0x005D5968]
        (No symbol) [0x005D5A55]
        (No symbol) [0x005E051B]
        BaseThreadInitThunk [0x7710FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x772B7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x772B7B8E+238]

**Comment by felciano** [comment] 2022-12-06 22:38
I'm seeing the same. Looks similar to issue #577, which I think might have been closed prematurely

**Comment by mrooney** [comment] 2022-12-07 14:36
Thanks, closing as a duplicate of #577

**Closed by mrooney** 2022-12-07 14:36 UTC
