### ISSUE TITLE
Double authentication prompt Email/2FA issue

### ISSUE THREAD

**Issue by chinmayjade** [mintapi/mintapi#276] opened 2021-08-20 02:01 UTC
I followed the workaround on issue #258 and set up 2FA MFA Authenticator token but still unable to get automatic MFA login working. It seems like Mint is doing both sending a verification code to my email and then also requiring the code from Authenticator to complete the login. 

Due to this, the code is exiting with errors:
`raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=92.0.4515.159)`

Full traceback: [https://gist.github.com/chinmayjade/dea7f7d1c86ed6d43b1d9d26cfd66960](url)

I have correctly set mfa_method='soft-token' and mfa_token=manual_key
manual_key is a var which stores the manual key from intuit.

Interestingly, I have set the backup method to text message, but I still get a email code every time.

Order of prompts: Email -> token

**Comment by KOEPKEJR** [comment] 2021-08-20 02:34
I’ve had the same issue as you and also tried the soft token fix. Regardless, I still get the email. I’ve poorly hacked the code to determine what mint wants (e.g email code or password) based on what UX control is visible.  My crappy workaround has been working 99% of the time for the past 6 months.

**Comment by mrooney** [comment] 2021-08-20 04:14
Does #272 address this issue by chance? If not, happy to review a PR that would handle this use-case :)

**Comment by chinmayjade** [comment] 2021-08-20 22:52
#272 fix does not seem to have any effect on this issue.

**Comment by jaron-l** [comment] 2021-09-09 13:50
Looks like this is a duplicate of #254

**Comment by mrooney** [comment] 2021-09-19 04:58
Duplicate of #254

**Closed by mrooney** 2021-09-19 04:58 UTC
