### ISSUE TITLE
mint.get_credit_score() causing cookie error

### ISSUE THREAD

**Issue by dzg** [mintapi/mintapi#332] opened 2021-11-01 17:53 UTC
```
mint.get_credit_score()
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 1091, in get_credit_score
   report = self.get_credit_report(limit=1, details=False)
 File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 1107, in get_credit_report
   response = self.get(
 File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 613, in get
   return self.driver.request('GET', url, **kwargs)
 File "/usr/local/lib/python3.9/site-packages/seleniumrequests/request.py", line 232, in request
   self.add_cookie(cookie_dict)
 File "/usr/local/lib/python3.9/site-packages/seleniumrequests/request.py", line 154, in add_cookie
   super(RequestsSessionMixin, self).add_cookie(cookie_dict)
 File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 894, in add_cookie
   self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
 File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
   self.error_handler.check_response(response)
 File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
   raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
 (Session info: chrome=95.0.4638.54)
Message: invalid cookie domain: Cookie 'domain' mismatch
 (Session info: chrome=95.0.4638.54)
```

**Comment by dzg** [comment] 2021-11-01 18:01
Also, after 'manually' logging in within chromedriver window:

\`\`\`mint.get\_credit\_score()  
Traceback (most recent call last):  
 File "\<stdin>", line 1, in \<module>  
 File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 1091, in get\_credit\_score  
   report = self.get\_credit\_report(limit=1, details=False)  
 File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 1107, in get\_credit\_report  
   response = self.get(  
 File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 613, in get  
   return self.driver.request('GET', url, \*\*kwargs)  
 File "/usr/local/lib/python3.9/site-packages/seleniumrequests/request.py", line 232, in request  
   self.add\_cookie(cookie\_dict)  
 File "/usr/local/lib/python3.9/site-packages/seleniumrequests/request.py", line 154, in add\_cookie  
   super(RequestsSessionMixin, self).add\_cookie(cookie\_dict)  
 File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 894, in add\_cookie  
   self.execute(Command.ADD\_COOKIE, {'cookie': cookie\_dict})  
 File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute  
   self.error\_handler.check\_response(response)  
 File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check\_response  
   raise exception\_class(message, screen, stacktrace)  
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch  
 (Session info: chrome=95.0.4638.54)

Message: invalid cookie domain: Cookie 'domain' mismatch  
 (Session info: chrome=95.0.4638.54)  
\`\`\`

**Comment by dzg** [comment] 2021-11-01 22:19
**SOLVED** by deleting my old `session_path` folder and letting mintapi re-create it.

**Comment by burkematthew** [comment] 2021-11-01 22:25
@dzg this appears to be a duplicate of #313 . We have a fix for this in a pending PR. #320

**Comment by mrooney** [comment] 2021-11-04 23:50
Duplicate of #313

**Closed by mrooney** 2021-11-04 23:50 UTC
