### ISSUE TITLE
Getting string indices must be integers error when calling mint.get_budgets in Python? 

### ISSUE THREAD

**Issue by jcsacto** [mintapi/mintapi#253] opened 2021-03-24 21:35 UTC
Greetings all, so I finally got past all the issues with the email only login prompt, but now I'm trying to do a simple call to mint.get_budgets() and getting the 'string indices must be integers' error.   Do we know of any issues going on with the budgets area of code by chance?  Please be advised, I am novice Python developer. : )

Thanks! 

Python: 
budgets = mint.get_budgets()

TypeError                                 Traceback (most recent call last)
<ipython-input-9-ab9c26f7088d> in <module>
      1 #Get this months budget data
----> 2 budgets = mint.get_budgets()
      3 

~\.conda\envs\mintEnv\lib\site-packages\mintapi\api.py in get_budgets(self, hist)
   1015                     category = self.get_category_object_from_id(budget['cat'], categories)
   1016                     budget['cat'] = category['name']
-> 1017                     budget['parent'] = category['parent']['name']
   1018 
   1019         return budgets

TypeError: string indices must be integers

**Comment by jaron-l** [comment] 2021-09-09 13:57
@mrooney this can probably be closed with #261 being already merged.

**Comment by mrooney** [comment] 2021-09-19 04:59
Thanks, I'll mark as a duplicate, and Jon I hope you are able to resolve with the latest version.

**Comment by mrooney** [comment] 2021-09-19 04:59
Duplicate of #261

**Closed by mrooney** 2021-09-19 04:59 UTC

**Comment by jcsacto** [comment] 2021-10-01 05:21
@mrooney  Thanks, unfortunately I'm now getting that error when trying to pull budget history, any advice? 
 mint.get_budgets(hist=2)

**Comment by mrooney** [comment] 2021-10-05 17:09
@jcsacto thanks for the update! Are you getting that with the latest mintapi, 1.53? If so, feel free to open a new report with our beautiful new bug template :D
