### ISSUE TITLE
selenium.common.exceptions.ElementNotInteractableException

### ISSUE THREAD

**Issue by BenZuser** [mintapi/mintapi#250] opened 2021-03-13 17:06 UTC
I am getting this error :

DevTools listening on ws://127.0.0.1:64972/devtools/browser/59512294-80b0-4fac-8e37-c43a2bd173bb
[0313/115719.445:INFO:CONSOLE(1)] "analytics performance metrics [object Object]", source: https://mint.intuit.com/handlebars/common_3.0.1189/common/cms/js/csa-init.js (1)
[0313/115719.489:INFO:CONSOLE(1)] "analytics performance metrics [object Object]", source: https://mint.intuit.com/handlebars/common_3.0.1189/common/cms/js/csa-init.js (1)
[0313/115719.490:INFO:CONSOLE(1)] "mtx-track-star.js has been loaded.", source: https://mint.intuit.com/handlebars/common/cms/js/track-star.js (1)
[0313/115719.678:INFO:CONSOLE(19)] "%cYou are using a cased client name (%cTurbotax11%c) in the bv.js URL.
        Please use this URL instead: %chttps://apps.bazaarvoice.com/deployments/turbotax11/main_site/production/en_US/bv.js%c.
        For details, see the Conversations Implementation section of https://knowledge.bazaarvoice.com. color: #0b6392; font-size:1.1em; text-decoration:none; font-weight:normal; color:black; font-size:1.1em; font-weight:bold; color: #0b6392; font-size:1.1em; text-decoration:none; font-weight:normal; font-size:1.0em; font-weight:lighter; color: #0b6392; font-size:1.1em; text-decoration:none; font-weight:normal;", source: https://apps.bazaarvoice.com/bv.js (19)
[0313/115722.787:INFO:CONSOLE(69)] "before load rule ran", source: https://accounts.intuit.com/iux-tealium/utag/intuit/cg-accounts/prod/utag.js (69)
[0313/115725.127:INFO:CONSOLE(700)] "RTP data channels is deprecated and will be removed in M90, around April 2021. Please use standard SCTP data channels instead. See https://www.chromestatus.com/features/6485681910054912 for more details.", source: https://pf.intuit.com/fp/check.js;CIS3SID=idHere?org_id=idHerej&session_id=idHere&nonce=nonceHere&pageid=1 (700)
[0313/115725.141:INFO:CONSOLE(599)] "Refused to connect to 'chrome-extension://ghbmnnjooekpmoecnnnilnnbdlolhkhi/page_embed_script.js' because it violates the following Content Security Policy directive: "connect-src 'self' wss://127.0.0.1:*".
", source: https://pf.intuit.com/fp/check.js;CIS3SID=idHere?org_id=idHere&session_id=idHere&nonce=nonceHere&pageid=1 (599)
[0313/115725.535:ERROR:stun_port.cc(76)] Binding error response: class=4 number=1 reason=Unauthorized
[0313/115726.023:ERROR:rtc_error.cc(17)] RTCError: RTCErrorDetail is NONE
Traceback (most recent call last):
  File ".\Mint.py", line 42, in <module>
    use_chromedriver_on_path=True
  File "C:\Users\ben\Apps\miniconda3\lib\site-packages\mintapi\api.py", line 451, in __init__
    chromedriver_download_path=chromedriver_download_path)
  File "C:\Users\ben\Apps\miniconda3\lib\site-packages\mintapi\api.py", line 539, in login_and_get_token
    chromedriver_download_path=chromedriver_download_path)
  File "C:\Users\ben\Apps\miniconda3\lib\site-packages\mintapi\api.py", line 304, in get_web_driver
    email_input.clear()
  File "C:\Users\ben\Apps\miniconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 95, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "C:\Users\ben\Apps\miniconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\ben\Apps\miniconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ben\Apps\miniconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=89.0.4389.82)

It seems to be related to a CSP issue? Is it something else?

**Comment by jrejaud** [comment] 2021-03-16 04:47
![image](https://user-images.githubusercontent.com/6202008/111257281-1368d680-85d8-11eb-8ec3-343b51fc960e.png)

I am having this issue as well, running the program in non-headless mode shows that it hangs on the login page (it's not inserting the email in the login field).

I suspect Mint must have changed the login process and this script hasn't caught up to the new changes yet...

**Comment by jsvullo** [comment] 2021-03-17 05:02
Getting this same error.

**Comment by kevko2020** [comment] 2021-05-30 00:56
Getting this still on the latest branch.

**Comment by jaron-l** [comment] 2021-09-09 14:02
@BenZuser, could verify what mintapi version you were using and if it still happens on the current release (1.49)? I am unable to reproduce.

**Comment by mrooney** [comment] 2021-09-19 05:01
Thanks @jaron-l ! Closing for now, feel free to let me know and we can re-open if it can be reproduced with the latest version!

**Closed by mrooney** 2021-09-19 05:01 UTC
